// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK_hobCAp7HeAXq1nzJUrZu0O4NMKGlC0',
    appId: '1:1032460508637:web:1dc718a7608f60ec78aa34',
    messagingSenderId: '1032460508637',
    projectId: 'whatsapp-97a3f',
    authDomain: 'whatsapp-97a3f.firebaseapp.com',
    storageBucket: 'whatsapp-97a3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV6GBc6R6VZygScVVPNJFI9W_ElGvolG8',
    appId: '1:1032460508637:android:3f977822101632c778aa34',
    messagingSenderId: '1032460508637',
    projectId: 'whatsapp-97a3f',
    storageBucket: 'whatsapp-97a3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCar_T6378PVD7X2SffPib2hUVrmRlAJkA',
    appId: '1:1032460508637:ios:03884232cbe6366d78aa34',
    messagingSenderId: '1032460508637',
    projectId: 'whatsapp-97a3f',
    storageBucket: 'whatsapp-97a3f.firebasestorage.app',
    androidClientId: '1032460508637-ngkkcte5auu9p1c3km37ld8raqkiiaif.apps.googleusercontent.com',
    iosClientId: '1032460508637-eqre5sj79bj64supi4vtl6dmtuusd3hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtspClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCar_T6378PVD7X2SffPib2hUVrmRlAJkA',
    appId: '1:1032460508637:ios:03884232cbe6366d78aa34',
    messagingSenderId: '1032460508637',
    projectId: 'whatsapp-97a3f',
    storageBucket: 'whatsapp-97a3f.firebasestorage.app',
    androidClientId: '1032460508637-ngkkcte5auu9p1c3km37ld8raqkiiaif.apps.googleusercontent.com',
    iosClientId: '1032460508637-eqre5sj79bj64supi4vtl6dmtuusd3hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.wtspClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK_hobCAp7HeAXq1nzJUrZu0O4NMKGlC0',
    appId: '1:1032460508637:web:deb3755b95a527d178aa34',
    messagingSenderId: '1032460508637',
    projectId: 'whatsapp-97a3f',
    authDomain: 'whatsapp-97a3f.firebaseapp.com',
    storageBucket: 'whatsapp-97a3f.firebasestorage.app',
  );

}